-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    migration_id character varying(150) COLLATE pg_catalog."default" NOT NULL,
    product_version character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk___ef_migrations_history PRIMARY KEY (migration_id)
);

CREATE TABLE IF NOT EXISTS public.categories
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.content_items
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    path text COLLATE pg_catalog."default",
    is_module boolean NOT NULL DEFAULT false,
    module_id integer,
    is_lesson boolean NOT NULL DEFAULT false,
    lesson_id integer,
    "order" integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_content_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.external_logins
(
    user_id integer NOT NULL,
    provider text COLLATE pg_catalog."default" NOT NULL,
    provider_user_id text COLLATE pg_catalog."default" NOT NULL,
    provider_data text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_external_logins PRIMARY KEY (user_id, provider)
);

CREATE TABLE IF NOT EXISTS public.lesson_types
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT pk_lesson_types PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lessons
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title text COLLATE pg_catalog."default" NOT NULL,
    content_item_id integer NOT NULL,
    type_id integer NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    xp integer NOT NULL DEFAULT 0,
    duration integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_lessons PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lifecycle_states
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT pk_lifecycle_states PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.module_tags
(
    module_id integer NOT NULL,
    tag_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_module_tags PRIMARY KEY (module_id, tag_id)
);

CREATE TABLE IF NOT EXISTS public.modules
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    content_item_id integer NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    image_path text COLLATE pg_catalog."default",
    created_by integer,
    description text COLLATE pg_catalog."default",
    category_id integer,
    lifecycle_state_id integer NOT NULL,
    xp integer NOT NULL DEFAULT 0,
    duration integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_modules PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.permissions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT pk_permissions PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.progress_states
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT pk_progress_states PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    changeable boolean NOT NULL DEFAULT true,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tags
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_finished_lessons
(
    user_id integer NOT NULL,
    lesson_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_finished_lessons PRIMARY KEY (user_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS public.user_module_progresses
(
    user_id integer NOT NULL,
    module_id integer NOT NULL,
    progress_state_id integer NOT NULL,
    CONSTRAINT pk_user_module_progresses PRIMARY KEY (user_id, module_id)
);

CREATE TABLE IF NOT EXISTS public.user_permissions
(
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_permissions PRIMARY KEY (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.user_profiles
(
    id integer NOT NULL,
    first_name text COLLATE pg_catalog."default",
    last_name text COLLATE pg_catalog."default",
    display_name text COLLATE pg_catalog."default" NOT NULL,
    xp integer NOT NULL DEFAULT 0,
    level integer NOT NULL DEFAULT 1,
    avatar_path text COLLATE pg_catalog."default",
    bio text COLLATE pg_catalog."default",
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_profiles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_name text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    email_verified boolean NOT NULL DEFAULT false,
    phone_number text COLLATE pg_catalog."default",
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    require_password_reset boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.external_logins
    ADD CONSTRAINT fk_external_logins_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT fk_lessons_content_items_content_item_id FOREIGN KEY (content_item_id)
    REFERENCES public.content_items (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_lessons_content_item_id
    ON public.lessons(content_item_id);


ALTER TABLE IF EXISTS public.lessons
    ADD CONSTRAINT fk_lessons_lesson_types_type_id FOREIGN KEY (type_id)
    REFERENCES public.lesson_types (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_lessons_type_id
    ON public.lessons(type_id);


ALTER TABLE IF EXISTS public.module_tags
    ADD CONSTRAINT fk_module_tags_modules_module_id FOREIGN KEY (module_id)
    REFERENCES public.modules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_module_tags_module_id
    ON public.module_tags(module_id);


ALTER TABLE IF EXISTS public.module_tags
    ADD CONSTRAINT fk_module_tags_tags_tag_id FOREIGN KEY (tag_id)
    REFERENCES public.tags (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_module_tags_tag_id
    ON public.module_tags(tag_id);


ALTER TABLE IF EXISTS public.modules
    ADD CONSTRAINT fk_modules_categories_category_id FOREIGN KEY (category_id)
    REFERENCES public.categories (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_modules_category_id
    ON public.modules(category_id);


ALTER TABLE IF EXISTS public.modules
    ADD CONSTRAINT fk_modules_content_items_content_item_id FOREIGN KEY (content_item_id)
    REFERENCES public.content_items (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_modules_content_item_id
    ON public.modules(content_item_id);


ALTER TABLE IF EXISTS public.modules
    ADD CONSTRAINT fk_modules_lifecycle_states_lifecycle_state_id FOREIGN KEY (lifecycle_state_id)
    REFERENCES public.lifecycle_states (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_modules_lifecycle_state_id
    ON public.modules(lifecycle_state_id);


ALTER TABLE IF EXISTS public.modules
    ADD CONSTRAINT fk_modules_users_created_by FOREIGN KEY (created_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_modules_created_by
    ON public.modules(created_by);


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_role_permissions_permissions_permission_id FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_role_permissions_permission_id
    ON public.role_permissions(permission_id);


ALTER TABLE IF EXISTS public.role_permissions
    ADD CONSTRAINT fk_role_permissions_roles_role_id FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_role_permissions_role_id
    ON public.role_permissions(role_id);


ALTER TABLE IF EXISTS public.user_finished_lessons
    ADD CONSTRAINT fk_user_finished_lessons_lessons_lesson_id FOREIGN KEY (lesson_id)
    REFERENCES public.lessons (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_finished_lessons_lesson_id
    ON public.user_finished_lessons(lesson_id);


ALTER TABLE IF EXISTS public.user_finished_lessons
    ADD CONSTRAINT fk_user_finished_lessons_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_finished_lessons_user_id
    ON public.user_finished_lessons(user_id);


ALTER TABLE IF EXISTS public.user_module_progresses
    ADD CONSTRAINT fk_user_module_progresses_modules_module_id FOREIGN KEY (module_id)
    REFERENCES public.modules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_module_progresses_module_id
    ON public.user_module_progresses(module_id);


ALTER TABLE IF EXISTS public.user_module_progresses
    ADD CONSTRAINT fk_user_module_progresses_progress_states_progress_state_id FOREIGN KEY (progress_state_id)
    REFERENCES public.progress_states (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_module_progresses_progress_state_id
    ON public.user_module_progresses(progress_state_id);


ALTER TABLE IF EXISTS public.user_module_progresses
    ADD CONSTRAINT fk_user_module_progresses_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_module_progresses_user_id
    ON public.user_module_progresses(user_id);


ALTER TABLE IF EXISTS public.user_permissions
    ADD CONSTRAINT fk_user_permissions_permissions_permission_id FOREIGN KEY (permission_id)
    REFERENCES public.permissions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_permissions_permission_id
    ON public.user_permissions(permission_id);


ALTER TABLE IF EXISTS public.user_permissions
    ADD CONSTRAINT fk_user_permissions_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_permissions_user_id
    ON public.user_permissions(user_id);


ALTER TABLE IF EXISTS public.user_profiles
    ADD CONSTRAINT fk_user_profiles_users_id FOREIGN KEY (id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS pk_user_profiles
    ON public.user_profiles(id);


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_user_roles_roles_role_id FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_roles_role_id
    ON public.user_roles(role_id);


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fk_user_roles_users_user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_user_roles_user_id
    ON public.user_roles(user_id);

END;